services:
    postgres:
        image: postgres
        container_name: pg_keycloak
        restart: unless-stopped
        environment:
            POSTGRES_DB: ${PG_DB_APP}
            POSTGRES_USER: ${PG_USER}
            POSTGRES_PASSWORD: ${PG_PASSWORD}
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
        ports:
            - "5432:5432"

    keycloak:
        image: quay.io/keycloak/keycloak
        container_name: keycloak
        command: start-dev
        restart: unless-stopped
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://postgres:5432/${PG_DB_KEYCLOAK}
            KC_DB_USERNAME: ${PG_USER}
            KC_DB_PASSWORD: ${PG_PASSWORD}
            KC_BOOTSTRAP_ADMIN_USERNAME: ${KC_ADMIN}
            KC_BOOTSTRAP_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
        volumes:
            - keycloak_data:/opt/keycloak/data
        ports:
            - "8080:8080"
        depends_on:
            - postgres

    pgadmin:
        image: dpage/pgadmin4
        container_name: pgadmin
        restart: unless-stopped
        environment:
            PGADMIN_DEFAULT_EMAIL: pgadmin@darkskullz9.com
            PGADMIN_DEFAULT_PASSWORD: d4rk5kU1lzDb
        ports:
            - "5050:80"
        depends_on:
            - postgres

volumes:
    pgdata:
    keycloak_data:
